name: Configure AWS Profile

inputs:
  aws_region: 
    description: Region to assume role with
    required: false
    default: eu-west-2
  aws_access_key: 
    description: AWS access key
    required: true
  aws_secret_key:
    description: AWS secret key
    required: true
  aws_profile_name:
    description: Profiles for each role to be created
    required: false
    default: default
  role_arn:
    description: role arn to assume
    required: true
  role_session_duration:
    description: "Duration of time in seconds before the token expires. Defaults to 1 Hour"
    default: 3600
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup AWS Profile 
      id: setup
      run: |
        aws configure set default.region ${{ inputs.aws_region }} > /dev/null 2>&1
        aws configure set aws_access_key_id ${{ inputs.aws_access_key}}
        aws configure set aws_secret_access_key ${{ inputs.aws_secret_key }}
        role=$(aws sts assume-role --role-arn ${{ inputs.role_arn }} --role-session-name ${{ inputs.aws_profile_name }} --duration-seconds ${{ inputs.role_session_duration }}) 
        export AWS_ACCESS_KEY_ID=$(echo $role | jq -r .Credentials.AccessKeyId) &>/dev/null
        export AWS_SECRET_ACCESS_KEY=$(echo $role | jq -r .Credentials.SecretAccessKey) &>/dev/null
        export AWS_SESSION_TOKEN=$(echo $role | jq -r .Credentials.SessionToken) &>/dev/null
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile ${{ inputs.aws_profile_name }} &>/dev/null
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile ${{ inputs.aws_profile_name }} &>/dev/null
        aws configure set aws_session_token $AWS_SESSION_TOKEN --profile ${{ inputs.aws_profile_name }} &>/dev/null
      shell: bash
